twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        profil_repository: '@App\Repository\ProfilUserRepository'
        categories_repository: '@App\Repository\CategoriesRepository'
        livres_repository: '@App\Repository\LivresRepository'
        comment_repository: '@App\Repository\CommentRepository'